- name: Run Pipeline Script
        env:
          MY_NAME: "최하은"
        run: |
          python <<EOF
          import requests
          import json
          import os
          from datetime import datetime

          now = datetime.now()
          minute = now.minute
          url = f"https://jsonplaceholder.typicode.com/posts/{(minute % 100) + 1}"
          
          response = requests.get(url)
          if response.status_code == 200:
              data = response.json()
              
              file_name = f"{os.environ['MY_NAME']}_test.json"
              file_path = f"./{file_name}"
              
              existing_data = []
              if os.path.exists(file_path):
                  with open(file_path, 'r', encoding='utf-8') as f:
                      try:
                          existing_data = json.load(f)
                      except json.JSONDecodeError:
                          existing_data = []
              
              existing_data.append(data)
              
              with open(file_path, 'w', encoding='utf-8') as f:
                  json.dump(existing_data, f, ensure_ascii=False, indent=4)
              print(f"Successfully saved to {file_path}")
          else:
              print("Failed to fetch data")
          EOF
          
      - name: Upload result file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.MY_NAME }}_test_result
          path: ./${{ env.MY_NAME }}_test.json
